#!/bin/sh
if [ $# -lt 2 ]; then
    echo "youtube-music-download <AUTHOR> <YoutubeURL>"
    echo "$#"
    exit 1
fi
youtube-dl --yes-playlist --ignore-errors --extract-audio --audio-format mp3 -o "/mnt/plex-hdd/music/$1/%(title)s.%(ext)s" "$2"
